-- Query: Dashboard login accounts + role-based access for the
--   offline-conversion pipeline monitor.
-- Generated by: pipeline-monitor app (sterlingx_portal_repo)
-- Dataset.table: sterlingx-insights.pipeline_monitoring.dashboard_users
-- Status: PENDING HUMAN REVIEW -- do not run without reviewing
--
-- role: 'admin' (full access incl. user management + firm config) |
--       'developer' (full data access, no user management, no firm config) |
--       'user' (only sees firms listed in assigned_firms)
--
-- password_hash is a bcrypt hash -- the app must never write a plaintext
-- password here. reset_token_hash is a SHA-256 hash of the raw reset
-- token emailed to the user -- the raw token itself is never stored.
--
-- BigQuery has no UNIQUE constraint. Email uniqueness is enforced at the
-- application layer (check-before-insert in src/lib/auth/users.ts) -- do
-- not assume the table itself prevents duplicate emails.

CREATE SCHEMA IF NOT EXISTS `sterlingx-insights.pipeline_monitoring`;

CREATE TABLE IF NOT EXISTS
  `sterlingx-insights.pipeline_monitoring.dashboard_users`
(
  user_id               STRING NOT NULL,
  name                  STRING NOT NULL,
  email                 STRING NOT NULL,
  password_hash         STRING NOT NULL,
  role                  STRING NOT NULL,          -- admin | developer | user
  assigned_firms        ARRAY<STRING>,             -- only meaningful for role = 'user'
  is_active             BOOL NOT NULL DEFAULT TRUE,
  reset_token_hash      STRING,
  reset_token_expires_at TIMESTAMP,
  created_at            TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP NOT NULL
);
