-- Query: Admin-editable active/paused firm list, per pipeline (Offline
--   Conversion, Pacing Report -- Waterfall Report has no firms, it's a
--   singleton pipeline). Replaces each pipeline's own hardcoded
--   defaultActiveFirms/defaultPausedFirms (see src/lib/pipelines/*.ts) as
--   the source of truth once this table has rows for that pipeline_key --
--   those constants remain the seed/fallback default when this table is
--   empty or missing for a given pipeline (see src/lib/firm-config.ts).
-- Generated by: pipeline-monitor app (sterlingx_portal_repo)
-- Dataset.table: sterlingx-insights.pipeline_monitoring.dashboard_firm_config
-- Status: PENDING HUMAN REVIEW -- do not run without reviewing
--
-- pipeline_key + slug together are the effective primary key -- the same
-- slug can legitimately appear under two different pipelines (e.g.
-- "cutrer" tracked separately for Offline Conversion and Pacing Report).

CREATE SCHEMA IF NOT EXISTS `sterlingx-insights.pipeline_monitoring`;

CREATE TABLE IF NOT EXISTS
  `sterlingx-insights.pipeline_monitoring.dashboard_firm_config`
(
  pipeline_key STRING NOT NULL,
  slug         STRING NOT NULL,
  display_name STRING NOT NULL,
  is_active    BOOL NOT NULL,   -- true = tracked/checked, false = paused
  updated_at   TIMESTAMP NOT NULL,
  updated_by   STRING           -- email of the admin who last changed this row
);
