-- Query: Admin-editable active/paused firm list for the offline-conversion
--   pipeline monitor. Replaces the hardcoded ACTIVE_FIRMS/PAUSED_FIRMS in
--   src/lib/accounts.ts as the source of truth once this table has rows --
--   accounts.ts's constants remain as the seed/fallback default when this
--   table is empty or missing (see src/lib/firm-config.ts).
-- Generated by: pipeline-monitor app (sterlingx_portal_repo)
-- Dataset.table: rc-datamart-report-082025.pipeline_monitoring.dashboard_firm_config
-- Status: PENDING HUMAN REVIEW -- do not run without reviewing

CREATE SCHEMA IF NOT EXISTS `rc-datamart-report-082025.pipeline_monitoring`;

CREATE TABLE IF NOT EXISTS
  `rc-datamart-report-082025.pipeline_monitoring.dashboard_firm_config`
(
  slug         STRING NOT NULL,
  display_name STRING NOT NULL,
  is_active    BOOL NOT NULL,   -- true = tracked/checked, false = paused
  updated_at   TIMESTAMP NOT NULL,
  updated_by   STRING           -- email of the admin who last changed this row
);
