-- Query: Offline conversion pipeline health snapshot -- one row per active
--   firm per checkup run (daily via Cloud Scheduler -> POST
--   /api/offline-conversion-checkup, or on-demand via the dashboard's
--   "Check Now" button).
-- Generated by: pipeline-monitor app (sterlingx_portal_repo)
-- Dataset.table: sterlingx-insights.pipeline_monitoring.offline_conversion_health_status
-- Status: PENDING HUMAN REVIEW -- do not run without reviewing
--
-- stages_json holds the full per-stage StageResult[] array (table refs, row
-- counts, max dates) as JSON, so a snapshot is self-contained without
-- needing to re-query the source tables to see what a past run found.

CREATE SCHEMA IF NOT EXISTS `sterlingx-insights.pipeline_monitoring`;

CREATE TABLE IF NOT EXISTS
  `sterlingx-insights.pipeline_monitoring.offline_conversion_health_status`
(
  checked_at  TIMESTAMP NOT NULL,
  firm        STRING NOT NULL,
  verdict     STRING NOT NULL,   -- green | yellow | red
  notes       STRING,            -- pipe-separated human-readable notes
  stages_json STRING              -- JSON-encoded StageResult[] for this run
)
PARTITION BY DATE(checked_at);
