-- Query: Pipeline health snapshot -- one row per active firm (or one row
--   for a singleton pipeline) per checkup run, across every pipeline this
--   app tracks (Offline Conversion, Waterfall Report, Pacing Report, and
--   any added later -- see src/lib/pipelines/index.ts), daily via Cloud
--   Scheduler -> POST /api/checkup/[pipeline], or on-demand via the
--   dashboard's "Check Now" button.
-- Generated by: pipeline-monitor app (sterlingx_portal_repo)
-- Dataset.table: sterlingx-insights.pipeline_monitoring.pipeline_health_status
-- Status: PENDING HUMAN REVIEW -- do not run without reviewing
--
-- Renamed from offline_conversion_health_status.sql now that it holds
-- snapshots for every pipeline, not just Offline Conversion -- added
-- pipeline_key. Nothing has been applied to production yet (confirmed
-- this session), so this is a plain rename, not a migration.
--
-- stages_json holds the full per-stage StageResult[] array (table refs, row
-- counts, max dates) as JSON, so a snapshot is self-contained without
-- needing to re-query the source tables to see what a past run found.

CREATE SCHEMA IF NOT EXISTS `sterlingx-insights.pipeline_monitoring`;

CREATE TABLE IF NOT EXISTS
  `sterlingx-insights.pipeline_monitoring.pipeline_health_status`
(
  checked_at   TIMESTAMP NOT NULL,
  pipeline_key STRING NOT NULL,   -- e.g. "offline_conversion", "waterfall_report", "pacing_report"
  firm         STRING NOT NULL,   -- firm slug, or the pipeline_key itself for a singleton pipeline
  verdict      STRING NOT NULL,   -- green | yellow | red
  notes        STRING,            -- pipe-separated human-readable notes
  stages_json  STRING             -- JSON-encoded StageResult[] for this run
)
PARTITION BY DATE(checked_at)
CLUSTER BY pipeline_key;
