CREATE OR REPLACE TABLE `sterlingx-insights.all_clients.Client_Weekly_Pacing_Roundup`
PARTITION BY week_starting
CLUSTER BY client_id, week_starting
OPTIONS (require_partition_filter = false)
AS

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.aurit_mediation.aurit_mediation_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.scott_m_brown.scott_m_brown_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.tde.tde_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.vdl.vdl_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.johnson_law_group.johnson_law_group_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.mayer_pink.meyer_pink_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.kalish_and_jaggars.kalish_and_jaggars_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.bruce_law.bruce_law_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.fanishe_family_law.fanish_family_law_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.arizona_family_law.arizona_family_law_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.cutrer.cutrer_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.drake_law_firm.drake_law_firm_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.gjesdahl_law.gjesdahl_law_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.haffner_law.haffner_law_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.lafrance.lafrance_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.lancaster.lancaster_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.michael_ireland_associates.ireland_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.sterling_lawyers.sterling_lawyers_weekly_roundup_table`

UNION ALL

SELECT
  client_id,
  client_name,
  week_starting,
  answered_calls,
  missed_calls,
  total_calls,
  web_form_submissions,
  leads,
  qualified_potential_clients,
  consultation_scheduled,
  consultation_completed,
  funded_agreements,
  created_at,
  updated_at
FROM `sterlingx-insights.the_ramage_law_group.ramage_law_weekly_roundup_table`;
